# Generated by Django 4.0.5 on 2023-04-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stol1', models.BooleanField(default=False, verbose_name='1 үстел')),
                ('stol2', models.BooleanField(default=False, verbose_name='2 үстел')),
                ('stol3', models.BooleanField(default=False, verbose_name='3 үстел')),
                ('stol4', models.BooleanField(default=False, verbose_name='4 үстел')),
                ('stol5', models.BooleanField(default=False, verbose_name='5 үстел')),
                ('stol6', models.BooleanField(default=False, verbose_name='6 үстел')),
                ('stol7', models.BooleanField(default=False, verbose_name='7 үстел')),
                ('stol8', models.BooleanField(default=False, verbose_name='8 үстел')),
                ('id_stol', models.IntegerField(default=1, verbose_name='Деректер базасындағы брондау номері')),
                ('parsing_data', models.IntegerField(default=0, verbose_name='Ардуинодан келген деректер')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='parking',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Паркингтегі бос орын саны'),
        ),
    ]
